name: 'publish'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: install frontend dependencies
        run: bun install --frozen-lockfile
        
      - name: build application
        run: bun run build
          
      # Check if one of the commands above generated any unexpected artifacts
      # (like types generation)
      - name: check if git is dirty
        run: |
          if [[ -n $(git status --porcelain) ]];
          then
          echo "git is dirty, make sure you ran the gen script"
          git status --porcelain
          exit 1;
          fi
        
        #see https://github.com/tauri-apps/tauri-action?tab=readme-ov-file for details
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'feathr. v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          args: ${{ matrix.args }}